---
- name: Check if the process is running
  command: "{{ was_install_location }}/profiles/{{ profile_name }}/bin/serverStatus.sh {{ servername }}"
  register: running
- debug:
    msg: "{{ running.stdout_lines }}"

